import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useUser, login, logout } from "../src/auth";


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeComponent/>
    </div>
  )
}

const HomeComponent: NextPage = () => {
  const user = useUser();

  const handleLogin = (): void => {
    login().catch((error) => console.error(error));
  };

  const handleLogout = (): void => {
    logout().catch((error) => console.error(error));
  };

  const handleFetch = (): void => {
    console.log(user)
    console.log(user?.getIdToken)
    user?.getIdToken().then(item => {
      console.log(item)
      fetch("http://localhost:8080/private", {
        headers: {
          'Authorization': `Bearer ${item}`
        },
      }).then(item => {
        console.log(item)
        return item.text()
      })
      .then(item => {
        console.log(item)
      })
    })
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Auth Example</title>
      </Head>

      <div>
        <h1>Auth Example</h1>
        {user !== null ? (
          <h2>ログインしている</h2>
        ) : (
          <h2>ログインしていない</h2>
        )}
        <button onClick={handleLogin}>ログイン</button>
        <button onClick={handleLogout}>ログアウト</button>
        <button onClick={handleFetch}>dd</button>
      </div>
    </div>
  );
};

export default Home
